#include "unity.h"

void setUp(void) {}
void tearDown(void) {}

/* test_cpu.c (legacy) */
void test_noop(void);
void test_inc_r8(void);
void test_dec_r8(void);
void test_inc_r16(void);
void test_dec_r16(void);
void test_add_hl_r16(void);
void test_zero_flag(void);

/* test_cpu_block0.c */
void test_ld_r16_imm16(void);
void test_inc_r16_all_pairs(void);
void test_ld_r8_imm8(void);
void test_rlca(void);
void test_rrca(void);
void test_rla(void);
void test_rra(void);
void test_cpl(void);
void test_scf(void);
void test_ccf(void);
void test_inc_r8_half_carry(void);
void test_inc_r8_hl_memory(void);
void test_zero_flag_inc_dec(void);
void test_ld_r16mem_a_bc(void);
void test_ld_a_r16mem_de(void);
void test_ld_r16mem_hli(void);
void test_ld_r16mem_hld(void);
void test_jr_imm8_positive(void);
void test_jr_imm8_negative(void);
void test_jr_imm8_zero_offset(void);
void test_jr_nz_taken(void);
void test_jr_nz_not_taken(void);
void test_jr_z_taken(void);
void test_jr_z_not_taken(void);
void test_jr_nc_taken(void);
void test_jr_nc_not_taken(void);
void test_jr_c_taken(void);
void test_jr_c_not_taken(void);
void test_ld_imm16_sp(void);

/* test_cpu_block1.c */
void test_ld_r8_r8_bc(void);
void test_ld_r8_r8_self(void);
void test_ld_a_hl(void);
void test_ld_hl_a(void);

/* test_cpu_block2.c */
void test_add_a_r8(void);
void test_add_a_r8_carry(void);
void test_add_a_r8_half_carry(void);
void test_add_a_r8_no_half_carry(void);
void test_adc_a_r8_with_carry(void);
void test_adc_a_r8_without_carry(void);
void test_adc_a_r8_half_carry(void);
void test_sub_a_r8(void);
void test_sub_a_r8_borrow(void);
void test_sub_a_r8_zero(void);
void test_sub_a_r8_half_borrow(void);
void test_sbc_a_r8(void);
void test_sbc_a_r8_borrow_with_carry(void);
void test_sbc_a_r8_zero(void);
void test_and_a_r8(void);
void test_and_a_r8_zero(void);
void test_xor_a_r8(void);
void test_xor_a_r8_nonzero(void);
void test_or_a_r8(void);
void test_or_a_r8_zero(void);
void test_cp_a_r8(void);
void test_cp_a_r8_borrow(void);
void test_cp_a_r8_half_borrow(void);
void test_daa_after_add_no_adjustment(void);
void test_daa_after_add_lower_nibble_overflow(void);
void test_daa_after_add_upper_nibble_overflow(void);
void test_daa_after_add_with_half_carry(void);
void test_daa_after_sub(void);
void test_daa_after_sub_with_half_borrow(void);
void test_daa_after_sub_with_carry(void);
void test_daa_after_sub_no_adjustment(void);
void test_alu_hl_memory(void);

/* test_cpu_block3.c */
void test_add_imm8(void);
void test_add_imm8_carry(void);
void test_add_imm8_half_carry(void);
void test_add_imm8_no_half_carry(void);
void test_adc_imm8_with_carry(void);
void test_adc_imm8_without_carry(void);
void test_adc_imm8_half_carry(void);
void test_sub_imm8(void);
void test_sub_imm8_borrow(void);
void test_sub_imm8_zero(void);
void test_sub_imm8_half_borrow(void);
void test_sbc_imm8(void);
void test_sbc_imm8_borrow_with_carry(void);
void test_sbc_imm8_zero(void);
void test_and_imm8(void);
void test_and_imm8_zero(void);
void test_xor_imm8(void);
void test_xor_imm8_nonzero(void);
void test_or_imm8(void);
void test_or_imm8_zero(void);
void test_cp_imm8(void);
void test_cp_imm8_borrow(void);
void test_cp_imm8_half_borrow(void);

/* test_cpu_cb.c */
void test_cb_rlc_b(void);
void test_cb_rlc_zero(void);
void test_cb_rlc_a(void);
void test_cb_rrc_c(void);
void test_cb_rrc_zero(void);
void test_cb_rrc_no_carry(void);
void test_cb_rl_d(void);
void test_cb_rl_with_carry(void);
void test_cb_rl_no_carry(void);
void test_cb_rr_e(void);
void test_cb_rr_with_carry(void);
void test_cb_rr_no_carry(void);
void test_cb_sla_h(void);
void test_cb_sla_carry(void);
void test_cb_sla_msb_set(void);
void test_cb_sra_l(void);
void test_cb_sra_sign_extend(void);
void test_cb_sra_no_carry(void);
void test_cb_swap_a(void);
void test_cb_swap_zero(void);
void test_cb_swap_same_nibbles(void);
void test_cb_srl_b(void);
void test_cb_srl_msb_cleared(void);
void test_cb_srl_carry(void);
void test_cb_rlc_hl(void);
void test_cb_srl_hl(void);
void test_cb_instruction_cycles(void);
void test_cb_bit_0_b_set(void);
void test_cb_bit_0_b_clear(void);
void test_cb_bit_3_c_set(void);
void test_cb_bit_3_c_clear(void);
void test_cb_bit_7_a_set(void);
void test_cb_bit_7_a_clear(void);
void test_cb_bit_0_hl_set(void);
void test_cb_bit_0_hl_clear(void);
void test_cb_res_0_b(void);
void test_cb_res_0_b_already_clear(void);
void test_cb_res_3_c(void);
void test_cb_res_7_a(void);
void test_cb_res_0_hl(void);
void test_cb_set_0_b(void);
void test_cb_set_0_b_already_set(void);
void test_cb_set_3_c(void);
void test_cb_set_7_a(void);
void test_cb_set_5_l(void);
void test_cb_set_0_hl(void);
void test_cb_bit_instruction_cycles(void);
void test_cb_res_instruction_cycles(void);
void test_cb_set_instruction_cycles(void);

/* test_cpu_block3_full.c */
void test_push_bc(void);
void test_push_de(void);
void test_push_hl(void);
void test_push_af(void);
void test_pop_bc(void);
void test_pop_af_clears_lower_nibble(void);
void test_pop_af(void);
void test_ret(void);
void test_ret_nz_taken(void);
void test_ret_nz_not_taken(void);
void test_ret_z_taken(void);
void test_ret_c_taken(void);
void test_ret_nc_not_taken(void);
void test_jp(void);
void test_jp_nz_taken(void);
void test_jp_nz_not_taken(void);
void test_jp_z_taken(void);
void test_jp_nc_taken(void);
void test_jp_c_taken(void);
void test_jp_hl(void);
void test_call(void);
void test_call_nz_taken(void);
void test_call_nz_not_taken(void);
void test_call_z_taken(void);
void test_call_c_taken(void);
void test_call_nc_not_taken(void);
void test_rst_00(void);
void test_rst_38(void);
void test_rst_10(void);
void test_ldh_c_a(void);
void test_ldh_imm8_a(void);
void test_ld_imm16_a(void);
void test_ldh_a_c(void);
void test_ldh_a_imm8(void);
void test_ld_a_imm16(void);
void test_add_sp_imm8_positive(void);
void test_add_sp_imm8_negative(void);
void test_add_sp_imm8_half_carry(void);
void test_add_sp_imm8_carry(void);
void test_ld_hl_sp_plus_imm8(void);
void test_ld_sp_hl(void);
void test_di_clears_ime(void);
void test_ei_schedules_ime(void);
void test_reti_returns_and_enables_ime(void);
void test_jp_cycles(void);
void test_jp_hl_cycles(void);
void test_call_cycles(void);
void test_ret_cycles(void);
void test_push_cycles(void);
void test_pop_cycles(void);
void test_rst_cycles(void);

/* test_decode.c */
void test_decode_block0(void);
void test_decode_block1(void);
void test_decode_block2(void);
void test_decode_block3_alu_imm8(void);
void test_decode_block3_unknown(void);

/* test_cpu_halt_stop.c */
void test_halt_sets_is_halted_ime_set(void);
void test_halt_sets_is_halted_ime_not_set_no_pending(void);
void test_halt_no_ime_pending_interrupt_pc_bug(void);
void test_stop_sets_is_stopped(void);
void test_stop_ignores_second_byte(void);

/* test_timers.c */
void test_div_starts_at_zero(void);
void test_div_increments_every_256_cycles(void);
void test_div_write_resets_divider(void);
void test_update_timers_increments_div_counter(void);
void test_tima_does_not_increment_when_disabled(void);
void test_tima_increments_at_4096hz(void);
void test_tima_increments_at_262144hz(void);
void test_tima_increments_at_65536hz(void);
void test_tima_increments_at_16384hz(void);
void test_tima_overflow_reloads_from_tma_and_triggers_interrupt(void);
void test_tima_overflow_preserves_other_if_bits(void);
void test_tac_clock_select_works_with_enable(void);
void test_multiple_tima_increments_in_one_call(void);
void test_multiple_overflow_in_one_call(void);
void test_div_rollover_independent_of_tima(void);
void test_tima_persists_across_toggle(void);
void test_div_counter_16bit_wraparound(void);

/* test_mmu.c */
void test_init_memory_zeroed(void);
void test_write_read_memory8(void);
void test_write_read_memory16(void);
void test_echo_ram_write_redirect(void);
void test_echo_ram_read_redirect(void);
void test_echo_ram_bidirectional(void);
void test_echo_ram_full_range_start(void);
void test_echo_ram_full_range_end(void);
void test_non_echo_not_affected(void);
void test_work_ram_independent_from_echo(void);
void test_mbc1_rom_bank_0_default_rom_mode(void);
void test_mbc1_rom_bank_1_default(void);
void test_mbc1_select_rom_bank_1(void);
void test_mbc1_bank_1_wraps_zero_to_one(void);
void test_mbc1_rom_mode_upper_bits(void);
void test_mbc1_ram_enable_disable(void);
void test_mbc1_external_ram_rom_mode_bank_0(void);
void test_mbc1_external_ram_mode_switch_bank(void);
void test_mbc1_ram_mode_maps_rom_bank_0(void);
void test_mbc1_write_to_rom_does_not_alter_rom(void);
void test_mbc1_switch_from_rom_to_ram_mode(void);
void test_mbc1_mode_switch_affects_bank_0_window(void);
void test_mbc1_rom_addr_wraps_modulo_num_banks(void);
void test_mbc1_ram_not_allocated_returns_ff(void);
void test_mbc1_ram_bank_wraps_modulo(void);

int main(void)
{
    UNITY_BEGIN();

    RUN_TEST(test_noop);
    RUN_TEST(test_inc_r8);
    RUN_TEST(test_dec_r8);
    RUN_TEST(test_inc_r16);
    RUN_TEST(test_dec_r16);
    RUN_TEST(test_add_hl_r16);
    RUN_TEST(test_zero_flag);

    RUN_TEST(test_ld_r16_imm16);
    RUN_TEST(test_inc_r16_all_pairs);
    RUN_TEST(test_ld_r8_imm8);
    RUN_TEST(test_rlca);
    RUN_TEST(test_rrca);
    RUN_TEST(test_rla);
    RUN_TEST(test_rra);
    RUN_TEST(test_cpl);
    RUN_TEST(test_scf);
    RUN_TEST(test_ccf);
    RUN_TEST(test_inc_r8_half_carry);
    RUN_TEST(test_inc_r8_hl_memory);
    RUN_TEST(test_zero_flag_inc_dec);
    RUN_TEST(test_ld_r16mem_a_bc);
    RUN_TEST(test_ld_a_r16mem_de);
    RUN_TEST(test_ld_r16mem_hli);
    RUN_TEST(test_ld_r16mem_hld);
    RUN_TEST(test_jr_imm8_positive);
    RUN_TEST(test_jr_imm8_negative);
    RUN_TEST(test_jr_imm8_zero_offset);
    RUN_TEST(test_jr_nz_taken);
    RUN_TEST(test_jr_nz_not_taken);
    RUN_TEST(test_jr_z_taken);
    RUN_TEST(test_jr_z_not_taken);
    RUN_TEST(test_jr_nc_taken);
    RUN_TEST(test_jr_nc_not_taken);
    RUN_TEST(test_jr_c_taken);
    RUN_TEST(test_jr_c_not_taken);
    RUN_TEST(test_ld_imm16_sp);

    RUN_TEST(test_ld_r8_r8_bc);
    RUN_TEST(test_ld_r8_r8_self);
    RUN_TEST(test_ld_a_hl);
    RUN_TEST(test_ld_hl_a);

    RUN_TEST(test_add_a_r8);
    RUN_TEST(test_add_a_r8_carry);
    RUN_TEST(test_add_a_r8_half_carry);
    RUN_TEST(test_add_a_r8_no_half_carry);
    RUN_TEST(test_adc_a_r8_with_carry);
    RUN_TEST(test_adc_a_r8_without_carry);
    RUN_TEST(test_adc_a_r8_half_carry);
    RUN_TEST(test_sub_a_r8);
    RUN_TEST(test_sub_a_r8_borrow);
    RUN_TEST(test_sub_a_r8_zero);
    RUN_TEST(test_sub_a_r8_half_borrow);
    RUN_TEST(test_sbc_a_r8);
    RUN_TEST(test_sbc_a_r8_borrow_with_carry);
    RUN_TEST(test_sbc_a_r8_zero);
    RUN_TEST(test_and_a_r8);
    RUN_TEST(test_and_a_r8_zero);
    RUN_TEST(test_xor_a_r8);
    RUN_TEST(test_xor_a_r8_nonzero);
    RUN_TEST(test_or_a_r8);
    RUN_TEST(test_or_a_r8_zero);
    RUN_TEST(test_cp_a_r8);
    RUN_TEST(test_cp_a_r8_borrow);
    RUN_TEST(test_cp_a_r8_half_borrow);
    RUN_TEST(test_daa_after_add_no_adjustment);
    RUN_TEST(test_daa_after_add_lower_nibble_overflow);
    RUN_TEST(test_daa_after_add_upper_nibble_overflow);
    RUN_TEST(test_daa_after_add_with_half_carry);
    RUN_TEST(test_daa_after_sub);
    RUN_TEST(test_daa_after_sub_with_half_borrow);
    RUN_TEST(test_daa_after_sub_with_carry);
    RUN_TEST(test_daa_after_sub_no_adjustment);
    RUN_TEST(test_alu_hl_memory);

    RUN_TEST(test_add_imm8);
    RUN_TEST(test_add_imm8_carry);
    RUN_TEST(test_add_imm8_half_carry);
    RUN_TEST(test_add_imm8_no_half_carry);
    RUN_TEST(test_adc_imm8_with_carry);
    RUN_TEST(test_adc_imm8_without_carry);
    RUN_TEST(test_adc_imm8_half_carry);
    RUN_TEST(test_sub_imm8);
    RUN_TEST(test_sub_imm8_borrow);
    RUN_TEST(test_sub_imm8_zero);
    RUN_TEST(test_sub_imm8_half_borrow);
    RUN_TEST(test_sbc_imm8);
    RUN_TEST(test_sbc_imm8_borrow_with_carry);
    RUN_TEST(test_sbc_imm8_zero);
    RUN_TEST(test_and_imm8);
    RUN_TEST(test_and_imm8_zero);
    RUN_TEST(test_xor_imm8);
    RUN_TEST(test_xor_imm8_nonzero);
    RUN_TEST(test_or_imm8);
    RUN_TEST(test_or_imm8_zero);
    RUN_TEST(test_cp_imm8);
    RUN_TEST(test_cp_imm8_borrow);
    RUN_TEST(test_cp_imm8_half_borrow);

    RUN_TEST(test_cb_rlc_b);
    RUN_TEST(test_cb_rlc_zero);
    RUN_TEST(test_cb_rlc_a);
    RUN_TEST(test_cb_rrc_c);
    RUN_TEST(test_cb_rrc_zero);
    RUN_TEST(test_cb_rrc_no_carry);
    RUN_TEST(test_cb_rl_d);
    RUN_TEST(test_cb_rl_with_carry);
    RUN_TEST(test_cb_rl_no_carry);
    RUN_TEST(test_cb_rr_e);
    RUN_TEST(test_cb_rr_with_carry);
    RUN_TEST(test_cb_rr_no_carry);
    RUN_TEST(test_cb_sla_h);
    RUN_TEST(test_cb_sla_carry);
    RUN_TEST(test_cb_sla_msb_set);
    RUN_TEST(test_cb_sra_l);
    RUN_TEST(test_cb_sra_sign_extend);
    RUN_TEST(test_cb_sra_no_carry);
    RUN_TEST(test_cb_swap_a);
    RUN_TEST(test_cb_swap_zero);
    RUN_TEST(test_cb_swap_same_nibbles);
    RUN_TEST(test_cb_srl_b);
    RUN_TEST(test_cb_srl_msb_cleared);
    RUN_TEST(test_cb_srl_carry);
    RUN_TEST(test_cb_rlc_hl);
    RUN_TEST(test_cb_srl_hl);
    RUN_TEST(test_cb_instruction_cycles);
    RUN_TEST(test_cb_bit_0_b_set);
    RUN_TEST(test_cb_bit_0_b_clear);
    RUN_TEST(test_cb_bit_3_c_set);
    RUN_TEST(test_cb_bit_3_c_clear);
    RUN_TEST(test_cb_bit_7_a_set);
    RUN_TEST(test_cb_bit_7_a_clear);
    RUN_TEST(test_cb_bit_0_hl_set);
    RUN_TEST(test_cb_bit_0_hl_clear);
    RUN_TEST(test_cb_res_0_b);
    RUN_TEST(test_cb_res_0_b_already_clear);
    RUN_TEST(test_cb_res_3_c);
    RUN_TEST(test_cb_res_7_a);
    RUN_TEST(test_cb_res_0_hl);
    RUN_TEST(test_cb_set_0_b);
    RUN_TEST(test_cb_set_0_b_already_set);
    RUN_TEST(test_cb_set_3_c);
    RUN_TEST(test_cb_set_7_a);
    RUN_TEST(test_cb_set_5_l);
    RUN_TEST(test_cb_set_0_hl);
    RUN_TEST(test_cb_bit_instruction_cycles);
    RUN_TEST(test_cb_res_instruction_cycles);
    RUN_TEST(test_cb_set_instruction_cycles);

    RUN_TEST(test_push_bc);
    RUN_TEST(test_push_de);
    RUN_TEST(test_push_hl);
    RUN_TEST(test_push_af);
    RUN_TEST(test_pop_bc);
    RUN_TEST(test_pop_af_clears_lower_nibble);
    RUN_TEST(test_pop_af);
    RUN_TEST(test_ret);
    RUN_TEST(test_ret_nz_taken);
    RUN_TEST(test_ret_nz_not_taken);
    RUN_TEST(test_ret_z_taken);
    RUN_TEST(test_ret_c_taken);
    RUN_TEST(test_ret_nc_not_taken);
    RUN_TEST(test_jp);
    RUN_TEST(test_jp_nz_taken);
    RUN_TEST(test_jp_nz_not_taken);
    RUN_TEST(test_jp_z_taken);
    RUN_TEST(test_jp_nc_taken);
    RUN_TEST(test_jp_c_taken);
    RUN_TEST(test_jp_hl);
    RUN_TEST(test_call);
    RUN_TEST(test_call_nz_taken);
    RUN_TEST(test_call_nz_not_taken);
    RUN_TEST(test_call_z_taken);
    RUN_TEST(test_call_c_taken);
    RUN_TEST(test_call_nc_not_taken);
    RUN_TEST(test_rst_00);
    RUN_TEST(test_rst_38);
    RUN_TEST(test_rst_10);
    RUN_TEST(test_ldh_c_a);
    RUN_TEST(test_ldh_imm8_a);
    RUN_TEST(test_ld_imm16_a);
    RUN_TEST(test_ldh_a_c);
    RUN_TEST(test_ldh_a_imm8);
    RUN_TEST(test_ld_a_imm16);
    RUN_TEST(test_add_sp_imm8_positive);
    RUN_TEST(test_add_sp_imm8_negative);
    RUN_TEST(test_add_sp_imm8_half_carry);
    RUN_TEST(test_add_sp_imm8_carry);
    RUN_TEST(test_ld_hl_sp_plus_imm8);
    RUN_TEST(test_ld_sp_hl);
    RUN_TEST(test_di_clears_ime);
    RUN_TEST(test_ei_schedules_ime);
    RUN_TEST(test_reti_returns_and_enables_ime);
    RUN_TEST(test_jp_cycles);
    RUN_TEST(test_jp_hl_cycles);
    RUN_TEST(test_call_cycles);
    RUN_TEST(test_ret_cycles);
    RUN_TEST(test_push_cycles);
    RUN_TEST(test_pop_cycles);
    RUN_TEST(test_rst_cycles);

    RUN_TEST(test_decode_block0);
    RUN_TEST(test_decode_block1);
    RUN_TEST(test_decode_block2);
    RUN_TEST(test_decode_block3_alu_imm8);
    RUN_TEST(test_decode_block3_unknown);

    /* Timer tests */
    RUN_TEST(test_div_starts_at_zero);
    RUN_TEST(test_div_increments_every_256_cycles);
    RUN_TEST(test_div_write_resets_divider);
    RUN_TEST(test_update_timers_increments_div_counter);
    RUN_TEST(test_tima_does_not_increment_when_disabled);
    RUN_TEST(test_tima_increments_at_4096hz);
    RUN_TEST(test_tima_increments_at_262144hz);
    RUN_TEST(test_tima_increments_at_65536hz);
    RUN_TEST(test_tima_increments_at_16384hz);
    RUN_TEST(test_tima_overflow_reloads_from_tma_and_triggers_interrupt);
    RUN_TEST(test_tima_overflow_preserves_other_if_bits);
    RUN_TEST(test_tac_clock_select_works_with_enable);
    RUN_TEST(test_multiple_tima_increments_in_one_call);
    RUN_TEST(test_multiple_overflow_in_one_call);
    RUN_TEST(test_div_rollover_independent_of_tima);
    RUN_TEST(test_tima_persists_across_toggle);
    RUN_TEST(test_div_counter_16bit_wraparound);

    /* HALT/STOP tests */
    RUN_TEST(test_halt_sets_is_halted_ime_set);
    RUN_TEST(test_halt_sets_is_halted_ime_not_set_no_pending);
    RUN_TEST(test_halt_no_ime_pending_interrupt_pc_bug);
    RUN_TEST(test_stop_sets_is_stopped);
    RUN_TEST(test_stop_ignores_second_byte);

    RUN_TEST(test_init_memory_zeroed);
    RUN_TEST(test_write_read_memory8);
    RUN_TEST(test_write_read_memory16);
    RUN_TEST(test_echo_ram_write_redirect);
    RUN_TEST(test_echo_ram_read_redirect);
    RUN_TEST(test_echo_ram_bidirectional);
    RUN_TEST(test_echo_ram_full_range_start);
    RUN_TEST(test_echo_ram_full_range_end);
    RUN_TEST(test_non_echo_not_affected);
    RUN_TEST(test_work_ram_independent_from_echo);

    RUN_TEST(test_mbc1_rom_bank_0_default_rom_mode);
    RUN_TEST(test_mbc1_rom_bank_1_default);
    RUN_TEST(test_mbc1_select_rom_bank_1);
    RUN_TEST(test_mbc1_bank_1_wraps_zero_to_one);
    RUN_TEST(test_mbc1_rom_mode_upper_bits);
    RUN_TEST(test_mbc1_ram_enable_disable);
    RUN_TEST(test_mbc1_external_ram_rom_mode_bank_0);
    RUN_TEST(test_mbc1_external_ram_mode_switch_bank);
    RUN_TEST(test_mbc1_ram_mode_maps_rom_bank_0);
    RUN_TEST(test_mbc1_write_to_rom_does_not_alter_rom);
    RUN_TEST(test_mbc1_switch_from_rom_to_ram_mode);
    RUN_TEST(test_mbc1_mode_switch_affects_bank_0_window);
    RUN_TEST(test_mbc1_rom_addr_wraps_modulo_num_banks);
    RUN_TEST(test_mbc1_ram_not_allocated_returns_ff);
    RUN_TEST(test_mbc1_ram_bank_wraps_modulo);

    return UNITY_END();
}